# Generated by Django 5.2.10 on 2026-01-23 17:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('oib', models.CharField(blank=True, default='', max_length=11)),
            ],
            options={
                'verbose_name': 'Ledger',
                'verbose_name_plural': 'Ledgers',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('ASSET', 'Imovina'), ('LIABILITY', 'Obveze'), ('EQUITY', 'Kapital'), ('INCOME', 'Prihodi'), ('EXPENSE', 'Rashodi')], max_length=16)),
                ('normal_side', models.CharField(choices=[('D', 'Duguje'), ('P', 'Potrazuje')], max_length=1)),
                ('is_postable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.ledger')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['ledger_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Nacrt'), ('POSTED', 'Proknjizeno'), ('VOID', 'Stornirano')], default='DRAFT', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounting.ledger')),
            ],
            options={
                'verbose_name': 'Journal entry',
                'verbose_name_plural': 'Journal entries',
                'ordering': ['ledger_id', '-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='accounting.ledger')),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'ordering': ['ledger_id', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_items', to='accounting.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Journal item',
                'verbose_name_plural': 'Journal items',
                'ordering': ['entry_id', 'id'],
                'indexes': [models.Index(fields=['entry', 'account'], name='accounting__entry_i_3022f3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='ck_item_non_negative'), models.CheckConstraint(condition=models.Q(models.Q(('debit', 0), ('credit__gt', 0)), models.Q(('credit', 0), ('debit__gt', 0)), _connector='OR'), name='ck_item_one_sided_amount')],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['ledger', 'date'], name='accounting__ledger__914551_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['ledger', 'number'], name='accounting__ledger__9ace31_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('ledger', 'number'), name='uq_entry_number_per_ledger'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['ledger', 'code'], name='accounting__ledger__fff094_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['ledger', 'parent'], name='accounting__ledger__9ab5e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('ledger', 'code'), name='uq_account_code_per_ledger'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='ck_account_code_not_empty'),
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['ledger', 'start_date', 'end_date'], name='accounting__ledger__86bd28_idx'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('ledger', 'name'), name='uq_period_name_per_ledger'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='ck_period_date_range_valid'),
        ),
    ]
