# Generated by Django 5.2.10 on 2026-01-23 19:35

import django.db.models.deletion
from django.db import migrations, models


def link_company_profile(apps, schema_editor):
    Ledger = apps.get_model("accounting", "Ledger")
    CompanyProfile = apps.get_model("configuration", "CompanyProfile")

    ledger = Ledger.objects.first()
    profile = CompanyProfile.objects.first()
    if ledger and profile and ledger.company_profile_id is None:
        ledger.company_profile = profile
        ledger.save(update_fields=["company_profile", "name", "oib"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_journalentry_reversed_entry'),
        ('configuration', '0012_documenttype_revenue_expense_fallbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='company_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='configuration.companyprofile'),
        ),
        migrations.RunPython(link_company_profile, migrations.RunPython.noop),
    ]
