# Generated by Django 5.2.10 on 2026-01-29 00:00

from django.db import migrations, models


def seed_external_org_id(apps, schema_editor):
    Ledger = apps.get_model("accounting", "Ledger")
    ledger = Ledger.objects.first()
    if ledger and ledger.external_organization_id is None:
        ledger.external_organization_id = 2
        ledger.save(update_fields=["external_organization_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_ledger_company_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="external_organization_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(seed_external_org_id, migrations.RunPython.noop),
    ]
