# Generated by Django 5.2.10 on 2026-01-29 00:00

from django.db import migrations, models


def seed_default_pos(apps, schema_editor):
    Pos = apps.get_model("pos", "Pos")
    if not Pos.objects.filter(external_pos_id=6).exists():
        Pos.objects.create(
            external_pos_id=6,
            name="POS 6",
            platform="windows",
            is_active=True,
            config={},
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_pos_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("platform", models.CharField(choices=[("windows", "Windows"), ("android", "Android"), ("ios", "iOS"), ("other", "Other")], default="windows", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "POS",
                "verbose_name_plural": "POS",
            },
        ),
        migrations.RunPython(seed_default_pos, migrations.RunPython.noop),
    ]
