# Generated by Django 5.2.10 on 2026-01-31 00:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0025_alter_drinkcategory_options_and_more'),
        ('pos', '0002_posprofile'),
        ('stock', '0036_stockcostsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.IntegerField()),
                ('issued_on', models.DateField()),
                ('issued_at', models.DateTimeField()),
                ('office_code', models.CharField(max_length=20)),
                ('device_code', models.CharField(max_length=20)),
                ('payment_type', models.CharField(choices=[('cash', 'Gotovina')], default='cash', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('fiscalized', 'Fiscalized'), ('error', 'Error')], default='draft', max_length=20)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('zki', models.CharField(blank=True, default='', max_length=64)),
                ('jir', models.CharField(blank=True, default='', max_length=64)),
                ('qr_payload', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_receipts', to=settings.AUTH_USER_MODEL)),
                ('pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='pos.pos')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_receipts', to='stock.warehouseid', to_field='rm_id')),
            ],
            options={
                'verbose_name': 'POS račun',
                'verbose_name_plural': 'POS računi',
            },
        ),
        migrations.CreateModel(
            name='PosReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('artikl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_receipt_items', to='artikli.artikl')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.posreceipt')),
            ],
            options={
                'verbose_name': 'Stavka POS računa',
                'verbose_name_plural': 'Stavke POS računa',
            },
        ),
        migrations.AddConstraint(
            model_name='posreceipt',
            constraint=models.UniqueConstraint(fields=('office_code', 'device_code', 'issued_on', 'receipt_number'), name='uq_pos_receipt_number'),
        ),
    ]
