# Generated by Django 5.2.10 on 2026-01-31 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_posreceipt_posreceiptitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posreceipt',
            name='storno_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storno_receipt', to='pos.posreceipt'),
        ),
        migrations.AlterField(
            model_name='posreceipt',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('fiscalized', 'Fiscalized'), ('storno', 'Storno'), ('error', 'Error')], default='draft', max_length=20),
        ),
    ]
