# Generated by Django 5.2.10 on 2026-01-31 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0025_alter_drinkcategory_options_and_more'),
        ('pos', '0004_posreceipt_storno_of_alter_posreceipt_status'),
        ('stock', '0036_stockcostsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Naziv')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('columns', models.PositiveIntegerField(default=6, verbose_name='Stupci')),
                ('rows', models.PositiveIntegerField(default=8, verbose_name='Redci')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
                ('note', models.TextField(blank=True, default='', verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screens', to='pos.pos', verbose_name='POS')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_screens', to='stock.warehouseid', verbose_name='Skladiste')),
            ],
            options={
                'verbose_name': 'POS ekran',
                'verbose_name_plural': 'POS ekrani',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PosScreenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=150, verbose_name='Naziv na tipki')),
                ('row', models.PositiveIntegerField(default=1, verbose_name='Red')),
                ('col', models.PositiveIntegerField(default=1, verbose_name='Stupac')),
                ('row_span', models.PositiveIntegerField(default=1, verbose_name='Visina')),
                ('col_span', models.PositiveIntegerField(default=1, verbose_name='Širina')),
                ('bg_color', models.CharField(blank=True, default='', max_length=20, verbose_name='Boja pozadine')),
                ('text_color', models.CharField(blank=True, default='', max_length=20, verbose_name='Boja teksta')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
                ('artikl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_screen_items', to='artikli.artikl', verbose_name='Artikl')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.posscreen', verbose_name='Ekran')),
            ],
            options={
                'verbose_name': 'Stavka POS ekrana',
                'verbose_name_plural': 'Stavke POS ekrana',
                'ordering': ['sort_order', 'row', 'col'],
                'constraints': [models.UniqueConstraint(fields=('screen', 'row', 'col'), name='uniq_pos_screen_position')],
            },
        ),
    ]
