# Generated by Django 5.2.10 on 2026-01-31 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_posscreen_posscreenitem'),
        ('stock', '0036_stockcostsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Naziv')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('is_default', models.BooleanField(default=False, verbose_name='Zadani')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
                ('note', models.TextField(blank=True, default='', verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modes', to='pos.pos', verbose_name='POS')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_modes', to='stock.warehouseid', verbose_name='Skladiste')),
            ],
            options={
                'verbose_name': 'POS mod rada',
                'verbose_name_plural': 'POS modovi rada',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PosModeScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='pos.posmode', verbose_name='Mod rada')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='pos.posscreen', verbose_name='Ekran')),
            ],
            options={
                'verbose_name': 'Ekran u modu',
                'verbose_name_plural': 'Ekrani u modu',
                'ordering': ['sort_order'],
                'constraints': [models.UniqueConstraint(fields=('mode', 'screen'), name='uniq_pos_mode_screen')],
            },
        ),
    ]
