# Generated by Django 5.2.10 on 2026-01-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_posmode_posmodescreen'),
    ]

    operations = [
        migrations.AddField(
            model_name='posprofile',
            name='pin_fail_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posprofile',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
