# Generated by Django 5.2.10 on 2026-02-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_posprofile_pin_fail_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posprofile',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='registriran'),
        ),
        migrations.AddField(
            model_name='posprofile',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posprofile',
            name='registered_device_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
