# Generated by Django 5.2.10 on 2026-02-01 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_posprofile_is_registered_posprofile_registered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='pos.pos', verbose_name='POS')),
            ],
            options={
                'verbose_name': 'POS uređaj',
                'verbose_name_plural': 'POS uređaji',
            },
        ),
    ]
