# Generated by Django 5.2.11 on 2026-02-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_pos_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='posprofile',
            name='pin_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
