# Generated by Django 5.2.11 on 2026-02-27 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_posprofile_pin_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='posdevice',
            name='print_receiver_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='PosPrinterInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='pos.posdevice')),
            ],
            options={
                'verbose_name': 'POS printer',
                'verbose_name_plural': 'POS printeri',
                'ordering': ('-is_default', 'name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='posdevice',
            name='bar_printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.posprinterinventory'),
        ),
        migrations.AddField(
            model_name='posdevice',
            name='receipt_printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.posprinterinventory'),
        ),
        migrations.AddConstraint(
            model_name='posprinterinventory',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='uq_pos_printer_device_name'),
        ),
    ]
