# Generated by Django 5.2.11 on 2026-03-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_seed_pos_printers_from_pos_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='posdevice',
            name='print_receiver_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
