# Generated by Django 5.2.10 on 2026-01-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_id', models.IntegerField(unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('inventory_quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity_difference', models.DecimalField(decimal_places=4, max_digits=12)),
                ('active', models.BooleanField(default=False)),
                ('base_group_order', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('order', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('product_order', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('base_group_name', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Stanje skladišta',
                'verbose_name_plural': 'Stanja skladišta',
            },
        ),
    ]
