# Generated by Django 5.2.10 on 2026-01-17 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0009_remove_artikldetail_point_of_issue_id_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestock',
            name='artikl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_stock_rows', to='artikli.artikl', to_field='rm_id'),
        ),
    ]
