# Generated by Django 5.2.10 on 2026-01-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_warehousestock_artikl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousestock',
            name='artikl',
        ),
    ]
