# Generated by Django 5.2.10 on 2026-01-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_warehousestock_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousestock',
            name='artikl',
        ),
    ]
