# Generated by Django 5.2.10 on 2026-01-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_remove_warehousestock_artikl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousestock',
            name='base_group_name',
        ),
    ]
