# Generated by Django 5.2.10 on 2026-01-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0008_remove_warehousestock_base_group_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductStockDS",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rm_id", models.IntegerField(unique=True)),
                ("product", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=12)),
                ("unit_of_measure", models.CharField(max_length=100)),
                ("input_value", models.DecimalField(decimal_places=4, max_digits=12)),
                ("base_group_name", models.CharField(max_length=255)),
                ("product_code", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Stanje artikla",
                "verbose_name_plural": "Stanja artikla",
            },
        ),
    ]
