# Generated by Django 5.2.10 on 2026-01-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0009_productstockds"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseId",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rm_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("hidden", models.BooleanField(default=False)),
                ("ordinal", models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
            ],
            options={
                "verbose_name": "Skladiste",
                "verbose_name_plural": "Skladista",
            },
        ),
    ]
