# Generated by Django 5.2.10 on 2026-01-18 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0011_remove_artikl_intrinsic_height_and_more'),
        ('stock', '0010_warehouseid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousestock',
            name='base_group_order',
        ),
        migrations.RemoveField(
            model_name='warehousestock',
            name='inventory_quantity',
        ),
        migrations.RemoveField(
            model_name='warehousestock',
            name='order',
        ),
        migrations.RemoveField(
            model_name='warehousestock',
            name='product_order',
        ),
        migrations.RemoveField(
            model_name='warehousestock',
            name='quantity_difference',
        ),
        migrations.RemoveField(
            model_name='warehousestock',
            name='rm_id',
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='base_group_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_stock_rows', to='artikli.artikl', to_field='rm_id'),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='product_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_rows', to='stock.warehouseid', to_field='rm_id'),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='wh_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
