# Generated by Django 5.2.10 on 2026-01-18 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0011_remove_artikl_intrinsic_height_and_more'),
        ('stock', '0011_remove_warehousestock_base_group_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='stock.warehouseid', to_field='rm_id')),
            ],
            options={
                'verbose_name': 'Inventura',
                'verbose_name_plural': 'Inventure',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('artikl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='artikli.artikl', to_field='rm_id')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.inventory')),
            ],
            options={
                'verbose_name': 'Stavka inventure',
                'verbose_name_plural': 'Stavke inventure',
            },
        ),
    ]
