# Generated by Django 5.2.10 on 2026-01-18 02:49

import django.db.models.deletion
from django.db import migrations, models


def prepare_inventoryitem_unit(apps, schema_editor):
    InventoryItem = apps.get_model("stock", "InventoryItem")
    UnitOfMeasureData = apps.get_model("artikli", "UnitOfMeasureData")

    unit_map = {}
    for unit in UnitOfMeasureData.objects.all():
        if unit.name:
            unit_map[unit.name.strip().lower()] = unit.pk

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE stock_inventoryitem ALTER COLUMN unit DROP NOT NULL;")

    for item in InventoryItem.objects.all().iterator():
        unit_value = (item.unit or "").strip()
        if not unit_value:
            item.unit = None
            item.save(update_fields=["unit"])
            continue

        unit_id = unit_map.get(unit_value.lower())
        item.unit = str(unit_id) if unit_id is not None else None
        item.save(update_fields=["unit"])


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0011_remove_artikl_intrinsic_height_and_more'),
        ('stock', '0013_alter_inventory_created_by'),
    ]

    operations = [
        migrations.RunPython(
            prepare_inventoryitem_unit,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_item_units', to='artikli.unitofmeasuredata'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
