# Generated by Django 5.2.10 on 2026-01-19 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0014_alter_artikl_rm_id'),
        ('stock', '0014_alter_inventoryitem_unit_alter_warehousestock_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('dont_change_inventory_quantity', models.BooleanField(default=False)),
                ('remaris_id', models.IntegerField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transfers', to='stock.warehouseid', to_field='rm_id')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='stock.warehouseid', to_field='rm_id')),
            ],
            options={
                'verbose_name': 'Međuskladišnica',
                'verbose_name_plural': 'Međuskladišnice',
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('artikl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_transfer_items', to='artikli.artikl', to_field='rm_id')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.warehousetransfer')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_transfer_item_units', to='artikli.unitofmeasuredata')),
            ],
            options={
                'verbose_name': 'Stavka međuskladišnice',
                'verbose_name_plural': 'Stavke međuskladišnice',
            },
        ),
    ]
