# Generated by Django 5.2.10 on 2026-01-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_warehousetransfer_warehousetransferitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousetransfer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
