# Generated by Django 5.2.10 on 2026-01-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('open', 'Otvoreno'), ('counted', 'Brojano'), ('closed', 'Zatvoreno')], default='open', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Napomena'),
        ),
    ]
