# Generated by Django 5.2.10 on 2026-01-23 20:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0016_deposit_artikl_deposit'),
        ('orders', '0023_warehouseinput_journal_entry_and_more'),
        ('stock', '0019_alter_inventory_status_alter_inventoryitem_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(choices=[('in', 'Ulaz'), ('out', 'Izlaz'), ('transfer', 'Transfer'), ('adjust', 'Ispravak')], max_length=20)),
                ('date', models.DateTimeField()),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Skladisno kretanje',
                'verbose_name_plural': 'Skladisna kretanja',
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField()),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('qty_in', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('qty_remaining', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('artikl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots', to='artikli.artikl', to_field='rm_id')),
                ('source_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots', to='orders.warehouseinputitem')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots', to='stock.warehouseid', to_field='rm_id')),
            ],
            options={
                'verbose_name': 'FIFO sloj',
                'verbose_name_plural': 'FIFO slojevi',
            },
        ),
        migrations.CreateModel(
            name='StockMoveLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('artikl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_move_lines', to='artikli.artikl', to_field='rm_id')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock.stockmove')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_move_lines', to='stock.warehouseid', to_field='rm_id')),
            ],
            options={
                'verbose_name': 'Stavka kretanja',
                'verbose_name_plural': 'Stavke kretanja',
            },
        ),
        migrations.CreateModel(
            name='StockAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='stock.stocklot')),
                ('move_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='stock.stockmoveline')),
            ],
            options={
                'verbose_name': 'FIFO alokacija',
                'verbose_name_plural': 'FIFO alokacije',
            },
        ),
    ]
