# Generated by Django 5.2.10 on 2026-01-23 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_warehouseinput_stock_move'),
        ('stock', '0020_stockmove_stocklot_stockmoveline_stockallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmoveline',
            name='source_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_move_lines', to='orders.warehouseinputitem'),
        ),
    ]
