# Generated by Django 5.2.10 on 2026-01-23 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_ledger_company_profile'),
        ('stock', '0021_stockmoveline_source_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmove',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_move', to='accounting.journalentry'),
        ),
    ]
