# Generated by Django 5.2.10 on 2026-01-23 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_stockmove_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmove',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves_out', to='stock.warehouseid', to_field='rm_id'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves_in', to='stock.warehouseid', to_field='rm_id'),
        ),
    ]
