# Generated by Django 5.2.10 on 2026-01-23 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_stockmove_from_warehouse_stockmove_to_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmove',
            name='reversed_move',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='stock.stockmove'),
        ),
    ]
