# Generated by Django 5.2.10 on 2026-01-23 20:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0016_deposit_artikl_deposit'),
        ('stock', '0024_stockmove_reversed_move'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('source_type', models.CharField(blank=True, default='', max_length=50)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('artikl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to='artikli.artikl', to_field='rm_id')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to='stock.warehouseid', to_field='rm_id')),
            ],
            options={
                'verbose_name': 'Rezervacija zalihe',
                'verbose_name_plural': 'Rezervacije zaliha',
            },
        ),
    ]
