# Generated by Django 5.2.10 on 2026-01-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_stockreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmove',
            name='purpose',
            field=models.CharField(blank=True, choices=[('sale', 'Prodaja'), ('consumption', 'Utrošak'), ('waste', 'Otpis'), ('adjustment', 'Inventurna korekcija')], default='', max_length=20),
        ),
    ]
