# Generated by Django 5.2.10 on 2026-01-23 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_ledger_company_profile'),
        ('stock', '0026_stockmove_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAccountingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cogs_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('inventory_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Konfiguracija robnog knjizenja',
                'verbose_name_plural': 'Konfiguracija robnog knjizenja',
            },
        ),
    ]
