# Generated by Django 5.2.10 on 2026-01-23 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0028_stockmove_sales_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockaccountingconfig',
            name='default_purchase_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stock.warehouseid', to_field='rm_id'),
        ),
        migrations.AddField(
            model_name='stockaccountingconfig',
            name='default_sale_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stock.warehouseid', to_field='rm_id'),
        ),
    ]
