# Generated by Django 5.2.10 on 2026-01-23 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0029_stockaccountingconfig_default_purchase_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockaccountingconfig',
            name='auto_replenish_on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockaccountingconfig',
            name='default_replenish_from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stock.warehouseid', to_field='rm_id'),
        ),
    ]
