# Generated by Django 5.2.10 on 2026-01-23 22:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0016_deposit_artikl_deposit'),
        ('stock', '0030_stockaccountingconfig_auto_replenish_on_sale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplenishRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artikl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenish_request_lines', to='artikli.artikl', to_field='rm_id')),
            ],
            options={
                'verbose_name': 'Replenish stavka',
                'verbose_name_plural': 'Replenish stavke',
            },
        ),
    ]
