# Generated by Django 5.2.10 on 2026-01-24 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_ledger_company_profile'),
        ('stock', '0031_replenishrequestline'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockaccountingconfig',
            name='default_cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='stockaccountingconfig',
            name='default_deposit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
    ]
