# Generated by Django 5.2.10 on 2026-01-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0032_stockaccountingconfig_default_cash_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestock',
            name='internal_avg_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='prosjecna cijena (interno)'),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='internal_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='stanje (interno)'),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='internal_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='interno azurirano'),
        ),
    ]
