# Generated by Django 5.2.10 on 2026-01-29 00:00

from django.db import migrations, models


def seed_external_location_id(apps, schema_editor):
    WarehouseId = apps.get_model("stock", "WarehouseId")
    target = WarehouseId.objects.filter(rm_id=5).first() or WarehouseId.objects.first()
    if target and target.external_location_id is None:
        target.external_location_id = 5
        target.save(update_fields=["external_location_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0033_warehousestock_internal_avg_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouseid",
            name="external_location_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(seed_external_location_id, migrations.RunPython.noop),
    ]
