# Generated by Codex on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0034_warehouseid_external_location_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehousetransfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("posted_internal", "Posted internal"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
