# Generated by Django 5.2.10 on 2026-01-30 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0025_alter_drinkcategory_options_and_more'),
        ('stock', '0035_warehousetransfer_status_posted_internal'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField(verbose_name='Datum')),
                ('qty_on_hand', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Kolicina')),
                ('avg_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Prosjecna cijena')),
                ('total_value', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Vrijednost')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Izracunato')),
                ('artikl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_snapshots', to='artikli.artikl', to_field='rm_id', verbose_name='Artikl')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_snapshots', to='stock.warehouseid', to_field='rm_id', verbose_name='Skladiste')),
            ],
            options={
                'verbose_name': 'Snapshot nabavne cijene',
                'verbose_name_plural': 'Snapshoti nabavnih cijena',
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'artikl', 'as_of_date'), name='uniq_stock_cost_snapshot')],
            },
        ),
    ]
