# Generated by Codex on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0038_inventory_counted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="Naziv"),
        ),
        migrations.AddField(
            model_name="inventory",
            name="note",
            field=models.TextField(blank=True, default="", verbose_name="Napomena"),
        ),
    ]

