# Generated by GPT-5.2 on 2026-05-08

from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("artikli", "0027_alter_artikl_tax_group_required"),
        ("contacts", "0007_set_supplier_show_prices_true"),
        ("stock", "0039_inventory_name_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierReturn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField(verbose_name="Datum")),
                ("reference", models.CharField(blank=True, default="", max_length=200, verbose_name="Referenca")),
                ("note", models.TextField(blank=True, default="", verbose_name="Napomena")),
                ("status", models.CharField(choices=[("draft", "Draft"), ("posted", "Posted"), ("cancelled", "Cancelled")], default="draft", max_length=20, verbose_name="Status")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Kreirano")),
                ("posted_at", models.DateTimeField(blank=True, null=True, verbose_name="Proknjiženo")),
                ("created_by", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="supplier_returns", to=settings.AUTH_USER_MODEL, verbose_name="Kreirao")),
                ("stock_move", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="supplier_return", to="stock.stockmove", verbose_name="Skladišno kretanje")),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="supplier_returns", to="contacts.supplier", verbose_name="Dobavljač")),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="supplier_returns", to="stock.warehouseid", to_field="rm_id", verbose_name="Skladište")),
            ],
            options={
                "verbose_name": "Povrat dobavljaču",
                "verbose_name_plural": "Povrati dobavljaču",
            },
        ),
        migrations.CreateModel(
            name="SupplierReturnItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=12, validators=[MinValueValidator(0)], verbose_name="Količina")),
                ("note", models.TextField(blank=True, default="", verbose_name="Napomena")),
                ("artikl", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="supplier_return_items", to="artikli.artikl", to_field="rm_id", verbose_name="Artikl")),
                ("supplier_return", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="stock.supplierreturn", verbose_name="Povrat")),
                ("unit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="supplier_return_item_units", to="artikli.unitofmeasuredata", verbose_name="JM")),
            ],
            options={
                "verbose_name": "Stavka povrata dobavljaču",
                "verbose_name_plural": "Stavke povrata dobavljaču",
            },
        ),
    ]

