# Generated by GPT-5.2 on 2026-05-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0032_supplierpricelist_name"),
        ("stock", "0041_alter_stockmove_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierreturn",
            name="source_warehouse_input",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_returns",
                to="orders.warehouseinput",
                verbose_name="Izvor (primka)",
            ),
        ),
    ]
