# Generated by Django 5.2.10 on 2026-01-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mailmessage',
            new_name='mailbox_app_mailbox_95acbf_idx',
            old_name='mailbox_app_mailbox_uid_idx',
        ),
        migrations.RenameIndex(
            model_name='mailmessage',
            new_name='mailbox_app_sent_at_ffc6b1_idx',
            old_name='mailbox_app_sent_at_idx',
        ),
    ]
