# Generated by Django 5.2.11 on 2026-02-22 04:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64, verbose_name='Label')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='Capacity')),
                ('shape', models.CharField(choices=[('round', 'Round'), ('square', 'Square'), ('rectangle', 'Rectangle'), ('other', 'Other')], default='square', max_length=20, verbose_name='Shape')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP')),
                ('width', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Height')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Layout',
                'verbose_name_plural': 'Layouts',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='uniq_barion_single_active_layout')],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('color', models.CharField(blank=True, default='', max_length=20, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='barion.layout', verbose_name='Layout')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['layout_id', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LayoutTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='X')),
                ('y', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Y')),
                ('w', models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Width')),
                ('h', models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Height')),
                ('rotation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-360), django.core.validators.MaxValueValidator(360)], verbose_name='Rotation')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('z_index', models.IntegerField(default=0, verbose_name='Z-index')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_tables', to='barion.layout', verbose_name='Layout')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layout_tables', to='barion.table', verbose_name='Table')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layout_tables', to='barion.zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Layout table',
                'verbose_name_plural': 'Layout tables',
                'ordering': ['layout_id', 'z_index', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('layout', 'name'), name='uniq_barion_zone_layout_name'),
        ),
        migrations.AddConstraint(
            model_name='layouttable',
            constraint=models.UniqueConstraint(fields=('layout', 'table'), name='uniq_barion_layout_table'),
        ),
    ]
