# Generated by Django 5.2.11 on 2026-02-22 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('FREE', 'Free'), ('OPEN', 'Open'), ('RESERVED', 'Reserved'), ('PAYMENT_PENDING', 'Payment pending'), ('BLOCKED', 'Blocked')], default='FREE', max_length=20, verbose_name='State')),
                ('open_check_id', models.BigIntegerField(blank=True, null=True, verbose_name='Open check ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layout_table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='barion.layouttable', verbose_name='Layout table')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barion_table_states', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Table state',
                'verbose_name_plural': 'Table states',
                'indexes': [models.Index(fields=['state'], name='idx_barion_ts_state'), models.Index(fields=['updated_at'], name='idx_barion_ts_updated')],
            },
        ),
    ]
