# Generated by Django 5.2.11 on 2026-02-22 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barion', '0002_tablestate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10, verbose_name='Status')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barion_checks_closed', to=settings.AUTH_USER_MODEL, verbose_name='Closed by')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barion_checks_opened', to=settings.AUTH_USER_MODEL, verbose_name='Opened by')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='barion.table', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Check',
                'verbose_name_plural': 'Checks',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['table', 'status'], name='idx_barion_check_table_status'), models.Index(fields=['status', 'updated_at'], name='idx_barion_chk_status_upd')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('table',), name='uniq_barion_open_check_per_table')],
            },
        ),
    ]
