# Generated by Django 5.2.11 on 2026-02-22 07:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0027_alter_artikl_tax_group_required'),
        ('barion', '0003_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artikl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barion_check_items', to='artikli.artikl')),
                ('barion_check', models.ForeignKey(db_column='check_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='barion.check', verbose_name='Check')),
            ],
            options={
                'verbose_name': 'Check item',
                'verbose_name_plural': 'Check items',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['barion_check', 'id'], name='idx_barion_ci_check_id')],
            },
        ),
    ]
