# Generated by Django 5.2.11 on 2026-02-22 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barion', '0004_checkitem'),
        ('pos', '0010_pos_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='pos_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barion_check', to='pos.posreceipt', verbose_name='POS receipt'),
        ),
    ]
