# Generated by Django 5.2.11 on 2026-02-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0027_alter_artikl_tax_group_required'),
        ('barion', '0005_check_pos_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkitem',
            name='round_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkitem',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkitem',
            name='sent_to_bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='checkitem',
            index=models.Index(fields=['barion_check', 'sent_to_bar'], name='idx_barion_ci_check_sent'),
        ),
        migrations.AddIndex(
            model_name='checkitem',
            index=models.Index(fields=['barion_check', 'round_number'], name='idx_barion_ci_check_round'),
        ),
    ]
