# Generated by Django 5.2.11 on 2026-02-23

import django.db.models.deletion
from django.db import migrations, models


def ensure_check_items_have_artikl(apps, schema_editor):
    CheckItem = apps.get_model("barion", "CheckItem")
    Artikl = apps.get_model("artikli", "Artikl")

    unresolved_ids = []
    for item in CheckItem.objects.filter(artikl__isnull=True).only("id", "product_name"):
        name = (item.product_name or "").strip()
        if not name:
            unresolved_ids.append(item.id)
            continue
        matches = Artikl.objects.filter(name__iexact=name).values_list("id", flat=True)[:2]
        match_ids = list(matches)
        if len(match_ids) == 1:
            item.artikl_id = match_ids[0]
            item.save(update_fields=["artikl"])
        else:
            unresolved_ids.append(item.id)

    if unresolved_ids:
        sample = ",".join(str(v) for v in unresolved_ids[:20])
        raise RuntimeError(
            "Ne mogu migrirati CheckItem bez artikla. "
            f"Riješite ručno stavke (id): {sample}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("barion", "0006_checkitem_round_number_checkitem_sent_at_and_more"),
        ("artikli", "0027_alter_artikl_tax_group_required"),
    ]

    operations = [
        migrations.RunPython(ensure_check_items_have_artikl, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="checkitem",
            name="artikl",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="barion_check_items",
                to="artikli.artikl",
            ),
        ),
        migrations.RemoveField(
            model_name="checkitem",
            name="product_name",
        ),
    ]
