# Generated by Django 5.2.11 on 2026-02-23 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barion', '0007_checkitem_require_artikl_remove_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLayoutAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User layout access',
                'verbose_name_plural': 'User layout accesses',
                'ordering': ['user_id', '-is_default', 'layout_id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='layout',
            name='uniq_barion_single_active_layout',
        ),
        migrations.AddField(
            model_name='userlayoutaccess',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='barion.layout', verbose_name='Layout'),
        ),
        migrations.AddField(
            model_name='userlayoutaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barion_layout_accesses', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddConstraint(
            model_name='userlayoutaccess',
            constraint=models.UniqueConstraint(fields=('user', 'layout'), name='uniq_barion_user_layout_access'),
        ),
        migrations.AddConstraint(
            model_name='userlayoutaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('user',), name='uniq_barion_user_default_layout_access'),
        ),
    ]
