# Generated by Django 5.2.11 on 2026-02-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barion', '0008_userlayoutaccess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkitem',
            name='line_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('STORNO', 'Storno'), ('GRATIS', 'Gratis')], db_index=True, default='NORMAL', max_length=10),
        ),
    ]
