# Generated by Django 5.2.11 on 2026-02-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barion', '0009_checkitem_line_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkitem',
            name='line_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('STORNO', 'Storno'), ('GRATIS', 'Gratis'), ('OTPIS', 'Otpis')], db_index=True, default='NORMAL', max_length=10),
        ),
    ]
