# Generated by Django 5.2.11 on 2026-02-24 03:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0027_alter_artikl_tax_group_required'),
        ('barion', '0010_alter_checkitem_line_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPopularitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_qty_30d', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('window_days', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artikl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barion_popularity_snapshot', to='artikli.artikl')),
            ],
            options={
                'verbose_name': 'Product popularity snapshot',
                'verbose_name_plural': 'Product popularity snapshots',
                'indexes': [models.Index(fields=['-sold_qty_30d'], name='idx_barion_pop_qty_desc'), models.Index(fields=['updated_at'], name='idx_barion_pop_updated')],
            },
        ),
    ]
