# Generated by Django 5.2.11 on 2026-02-24 14:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0011_posprofile_pin_verified_at"),
        ("barion", "0011_productpopularitysnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="payment_status",
            field=models.CharField(
                choices=[("UNPAID", "Unpaid"), ("PARTIAL", "Partial"), ("PAID", "Paid")],
                default="UNPAID",
                max_length=10,
                verbose_name="Payment status",
            ),
        ),
        migrations.AddField(
            model_name="check",
            name="settlement_status",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("PREPARED", "Prepared"),
                    ("CARD_CONFIRMED", "Card confirmed"),
                    ("READY_FOR_ISSUE", "Ready for issue"),
                    ("COMPLETE", "Complete"),
                ],
                default="NONE",
                max_length=20,
                verbose_name="Settlement status",
            ),
        ),
        migrations.CreateModel(
            name="SettlementPart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("method", models.CharField(choices=[("CASH", "Cash"), ("CARD", "Card")], max_length=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tip_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("fiscal_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("PREPARED", "Prepared"), ("CONFIRMED", "Confirmed")],
                        default="PREPARED",
                        max_length=12,
                    ),
                ),
                ("external_txn_id", models.CharField(blank=True, default="", max_length=100)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "barion_check",
                    models.ForeignKey(
                        db_column="check_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_parts",
                        to="barion.check",
                        verbose_name="Check",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="barion_settlement_parts_confirmed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="barion_settlement_parts",
                        to="pos.posreceipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Settlement part",
                "verbose_name_plural": "Settlement parts",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["barion_check", "status"], name="idx_barion_sp_check_status"),
                    models.Index(fields=["barion_check", "method"], name="idx_barion_sp_check_method"),
                    models.Index(fields=["external_txn_id"], name="idx_barion_sp_ext_txn"),
                ],
            },
        ),
    ]
