# Generated by Django 5.2.11 on 2026-02-24 16:10

from decimal import Decimal
from django.db import migrations, models


def backfill_settlementpart_amounts(apps, schema_editor):
    SettlementPart = apps.get_model("barion", "SettlementPart")
    for part in SettlementPart.objects.all().iterator():
        if part.status == "CONFIRMED":
            part.status = "PAID"
        amount = Decimal(str(part.amount or "0.00"))
        tip = Decimal(str(part.tip_amount or "0.00"))
        if part.method == "CARD":
            total_charged = (amount + tip).quantize(Decimal("0.01"))
            part.total_charged = total_charged
            part.fiscal_amount = total_charged
        else:
            part.tip_amount = Decimal("0.00")
            part.total_charged = amount.quantize(Decimal("0.01"))
            part.fiscal_amount = amount.quantize(Decimal("0.01"))
        part.save(update_fields=["status", "tip_amount", "total_charged", "fiscal_amount", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("barion", "0012_check_settlementpart_and_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlementpart",
            name="provider_ref",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="settlementpart",
            name="total_charged",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AlterField(
            model_name="settlementpart",
            name="status",
            field=models.CharField(
                choices=[("PREPARED", "Prepared"), ("PAID", "Paid"), ("FAILED", "Failed")],
                default="PREPARED",
                max_length=12,
            ),
        ),
        migrations.RunPython(backfill_settlementpart_amounts, migrations.RunPython.noop),
    ]
