# Generated by Django 5.2.11 on 2026-02-24 22:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barion', '0013_settlementpart_provider_ref_total_charged'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkitem',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='checkitem',
            name='paid_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
    ]
