# Generated by Django 5.2.11 on 2026-02-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barion', '0014_checkitem_paid_amount_checkitem_paid_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='pos_receipt',
        ),
    ]
