# Generated by Django 5.2.11 on 2026-02-26 22:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0027_alter_artikl_tax_group_required'),
        ('barion', '0021_alter_itemmodifiergroupassignment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBundleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_delta', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item bundle option',
                'verbose_name_plural': 'Item bundle options',
                'ordering': ['group_id', 'sort_order', 'artikl__name', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='checkitemmodifierselection',
            name='uniq_barion_check_item_modifier_option',
        ),
        migrations.AddField(
            model_name='checkitemmodifierselection',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='checkitemmodifierselection',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='check_item_selections', to='barion.itemmodifieroption'),
        ),
        migrations.AddField(
            model_name='itembundleoption',
            name='artikl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barion_bundle_options', to='artikli.artikl'),
        ),
        migrations.AddField(
            model_name='itembundleoption',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_options', to='barion.itemmodifiergroup'),
        ),
        migrations.AddField(
            model_name='checkitemmodifierselection',
            name='bundle_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='check_item_selections', to='barion.itembundleoption'),
        ),
        migrations.AddConstraint(
            model_name='checkitemmodifierselection',
            constraint=models.UniqueConstraint(condition=models.Q(('option__isnull', False)), fields=('check_item', 'option'), name='uniq_barion_check_item_modifier_option'),
        ),
        migrations.AddConstraint(
            model_name='checkitemmodifierselection',
            constraint=models.UniqueConstraint(condition=models.Q(('bundle_option__isnull', False)), fields=('check_item', 'bundle_option'), name='uniq_barion_check_item_bundle_option'),
        ),
        migrations.AddConstraint(
            model_name='checkitemmodifierselection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('option__isnull', False), ('bundle_option__isnull', True)), models.Q(('option__isnull', True), ('bundle_option__isnull', False)), _connector='OR'), name='chk_barion_check_item_one_option_source'),
        ),
        migrations.AddConstraint(
            model_name='itembundleoption',
            constraint=models.UniqueConstraint(fields=('group', 'artikl'), name='uniq_barion_bundle_option_group_artikl'),
        ),
    ]
