# Generated by Django 5.2.11 on 2026-02-27 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barion', '0022_itembundleoption_and_more'),
        ('pos', '0011_posprofile_pin_verified_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementpart',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='settlementpart',
            index=models.Index(fields=['provider'], name='idx_barion_sp_provider'),
        ),
    ]
