# Generated by Django 5.2.11 on 2026-02-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barion', '0023_settlementpart_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementpart',
            name='card_aid',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='card_application_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='card_auth_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='card_bank_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='card_brand',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='card_masked_pan',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='card_rrn',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='card_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
