# Generated by Django 5.2.11 on 2026-02-27 14:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barion', '0024_settlementpart_card_aid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementpart',
            name='provider_account_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='provider_action',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='provider_customer_trns',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='provider_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='provider_order_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='provider_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='provider_payment_method',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='provider_reference_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='provider_short_order_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='provider_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='provider_surcharge_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='provider_tid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='provider_transaction_date',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='provider_transaction_event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='provider_transaction_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlementpart',
            name='provider_verification_method',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
