# Generated by Django 5.2.11 on 2026-03-20 13:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barion', '0025_settlementpart_provider_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembundleoption',
            name='affects_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itembundleoption',
            name='stock_ratio',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
        migrations.CreateModel(
            name='ItemModifierDefaultSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_selections', to='barion.itemmodifiergroupassignment')),
                ('bundle_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_assignments', to='barion.itembundleoption')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_assignments', to='barion.itemmodifieroption')),
            ],
            options={
                'verbose_name': 'Item modifier default selection',
                'verbose_name_plural': 'Item modifier default selections',
                'ordering': ['assignment_id', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('option__isnull', False)), fields=('assignment', 'option'), name='uniq_barion_default_selection_assignment_option'), models.UniqueConstraint(condition=models.Q(('bundle_option__isnull', False)), fields=('assignment', 'bundle_option'), name='uniq_barion_default_selection_assignment_bundle_option'), models.CheckConstraint(condition=models.Q(models.Q(('option__isnull', False), ('bundle_option__isnull', True)), models.Q(('option__isnull', True), ('bundle_option__isnull', False)), _connector='OR'), name='chk_barion_default_selection_one_option_source')],
            },
        ),
    ]
