# Generated by Django 5.2.12 on 2026-04-08 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0028_rename_drinkcategory_to_category'),
        ('barion', '0027_barioncategory_barioncategorysettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarionCatalogState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_version', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Barion catalog state',
                'verbose_name_plural': 'Barion catalog state',
            },
        ),
        migrations.CreateModel(
            name='BarionCatalogSyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.BigIntegerField()),
                ('entity_type', models.CharField(choices=[('layout', 'Layout'), ('category', 'Category'), ('product', 'Product')], max_length=20)),
                ('entity_id', models.BigIntegerField()),
                ('operation', models.CharField(choices=[('upsert', 'Upsert'), ('delete', 'Delete')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Barion catalog sync event',
                'verbose_name_plural': 'Barion catalog sync events',
                'ordering': ['version', 'id'],
                'indexes': [models.Index(fields=['version'], name='idx_barion_cat_evt_ver'), models.Index(fields=['entity_type', 'entity_id'], name='idx_barion_cat_evt_ent'), models.Index(fields=['changed_at'], name='idx_barion_cat_evt_chg')],
            },
        ),
        migrations.CreateModel(
            name='BarionProductSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_version', models.BigIntegerField(default=1)),
                ('modifier_version', models.BigIntegerField(default=1)),
                ('last_catalog_version', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artikl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barion_sync_state', to='artikli.artikl')),
            ],
            options={
                'verbose_name': 'Barion product sync state',
                'verbose_name_plural': 'Barion product sync states',
            },
        ),
    ]
