# Generated by Django 5.2.10 on 2026-01-29 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("open", "Otvoreno"), ("closed", "Zatvoreno")], default="open", max_length=20)),
                ("closed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="closed_shifts", to=settings.AUTH_USER_MODEL)),
                ("opened_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="opened_shifts", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Smjena",
                "verbose_name_plural": "Smjene",
            },
        ),
        migrations.CreateModel(
            name="ShiftCashCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("OPENING", "Otvaranje"), ("CLOSING", "Zatvaranje")], max_length=10)),
                ("expected_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("counted_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("difference_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="shift_cash_counts", to=settings.AUTH_USER_MODEL)),
                ("shift", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cash_counts", to="operations.shift")),
            ],
            options={
                "verbose_name": "Prebrojavanje blagajne",
                "verbose_name_plural": "Prebrojavanja blagajne",
                "ordering": ["-created_at"],
            },
        ),
    ]
