# Generated by Django 5.2.10 on 2026-01-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfIssueData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Mjesto izdavanja',
                'verbose_name_plural': 'Mjesta izdavanja',
            },
        ),
    ]
