# Generated by Django 5.2.10 on 2026-01-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_remariscookie'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='naziv')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='adresa')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='postanski broj')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='grad')),
                ('oib', models.CharField(blank=True, default='', max_length=30, verbose_name='oib')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='telefon')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Podaci tvrtke',
                'verbose_name_plural': 'Podaci tvrtke',
            },
        ),
        migrations.CreateModel(
            name='OrderEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_template', models.CharField(default='Narudzba #{order_id}', max_length=255, verbose_name='predlozak subjecta')),
                ('body_template', models.TextField(default='U prilogu se nalazi narudzba {order_id}.', verbose_name='predlozak poruke')),
                ('active', models.BooleanField(default=True, verbose_name='aktivno')),
            ],
            options={
                'verbose_name': 'Predlozak emaila narudzbe',
                'verbose_name_plural': 'Predlosci emaila narudzbi',
            },
        ),
    ]
