# Generated by Django 5.2.10 on 2026-01-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_companyprofile_orderemailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='naziv')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='stopa')),
                ('code', models.CharField(blank=True, default='', max_length=50, verbose_name='sifra')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivno')),
            ],
            options={
                'verbose_name': 'Porezna grupa',
                'verbose_name_plural': 'Porezne grupe',
            },
        ),
    ]
