# Generated by Django 5.2.10 on 2026-01-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_taxgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='naziv')),
                ('code', models.CharField(blank=True, default='', max_length=50, verbose_name='sifra')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivno')),
            ],
            options={
                'verbose_name': 'Tip placanja',
                'verbose_name_plural': 'Tipovi placanja',
            },
        ),
    ]
