# Generated by Django 5.2.10 on 2026-01-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_paymenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='rm_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='rm id'),
        ),
    ]
