# Generated by Django 5.2.10 on 2026-01-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_paymenttype_rm_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='naziv')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='sifra')),
                ('direction', models.CharField(choices=[('in', 'Ulaz'), ('out', 'Izlaz')], max_length=3, verbose_name='smjer')),
                ('description', models.TextField(blank=True, default='', verbose_name='opis')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='redoslijed')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivno')),
            ],
            options={
                'verbose_name': 'Tip dokumenta',
                'verbose_name_plural': 'Tipovi dokumenata',
                'ordering': ('sort_order', 'name'),
            },
        ),
    ]
