# Generated by Django 5.2.10 on 2026-01-23 16:37

from django.db import migrations, models


def seed_primka_document_type(apps, schema_editor):
    DocumentType = apps.get_model("configuration", "DocumentType")
    DocumentType.objects.update_or_create(
        code="PRIMKA",
        defaults={
            "name": "Primka",
            "direction": "in",
            "description": "Ulaz robe - primka",
            "sort_order": 0,
            "is_active": True,
            "stock_account_code": "1310",
            "counterpart_account_code": "2200",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_documenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='counterpart_account_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='konto protustavke'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='stock_account_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='konto zalihe'),
        ),
        migrations.RunPython(seed_primka_document_type, migrations.RunPython.noop),
    ]
