# Generated by Django 5.2.10 on 2026-01-23 16:44

import django.db.models.deletion
from django.db import migrations, models


def migrate_documenttype_accounts(apps, schema_editor):
    Account = apps.get_model("configuration", "Account")
    DocumentType = apps.get_model("configuration", "DocumentType")

    for doc in DocumentType.objects.all():
        stock_code = getattr(doc, "stock_account_code", "") or ""
        counterpart_code = getattr(doc, "counterpart_account_code", "") or ""

        if stock_code:
            stock_account, _ = Account.objects.get_or_create(
                code=stock_code,
                defaults={"name": stock_code, "is_active": True},
            )
            doc.stock_account = stock_account

        if counterpart_code:
            counterpart_account, _ = Account.objects.get_or_create(
                code=counterpart_code,
                defaults={"name": counterpart_code, "is_active": True},
            )
            doc.counterpart_account = counterpart_account

        if stock_code or counterpart_code:
            doc.save(update_fields=["stock_account", "counterpart_account"])


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_documenttype_counterpart_account_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='sifra')),
                ('name', models.CharField(max_length=255, verbose_name='naziv')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivno')),
            ],
            options={
                'verbose_name': 'Konto',
                'verbose_name_plural': 'Konta',
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='documenttype',
            name='counterpart_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_types_counterpart', to='configuration.account', verbose_name='konto protustavke'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='stock_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_types_stock', to='configuration.account', verbose_name='konto zalihe'),
        ),
        migrations.RunPython(migrate_documenttype_accounts, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='documenttype',
            name='counterpart_account_code',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='stock_account_code',
        ),
    ]
