# Generated by Django 5.2.10 on 2026-01-26 16:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0013_consumption_tax_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGovernmentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='naziv')),
                ('oib', models.CharField(blank=True, max_length=11, null=True, verbose_name='OIB')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivno')),
            ],
            options={
                'verbose_name': 'JLS (grad/općina)',
                'verbose_name_plural': 'JLS (gradovi/općine)',
            },
        ),
        migrations.CreateModel(
            name='ConsumptionTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0.0200'), max_digits=5)),
                ('valid_from', models.DateField(verbose_name='vrijedi od')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='vrijedi do')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivno')),
                ('lgu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnp_rates', to='configuration.localgovernmentunit', verbose_name='JLS')),
            ],
            options={
                'verbose_name': 'Stopa poreza na potrošnju',
                'verbose_name_plural': 'Stope poreza na potrošnju',
                'indexes': [models.Index(fields=['lgu', 'valid_from'], name='configurati_lgu_id_e3a3f1_idx')],
            },
        ),
    ]
