# Generated by Django 5.2.10 on 2026-01-26 16:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_localgovernmentunit_consumptiontaxrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localgovernmentunit',
            options={'verbose_name': 'Grad / Općina (PnP)', 'verbose_name_plural': 'Gradovi / Općine (PnP)'},
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='lgu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.localgovernmentunit', verbose_name='Grad / općina (PnP)'),
        ),
        migrations.AddField(
            model_name='localgovernmentunit',
            name='pnp_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0200'), help_text='Stopa poreza na potrošnju (npr. 0.0200 za 2%)', max_digits=5, verbose_name='PnP stopa'),
        ),
        migrations.DeleteModel(
            name='ConsumptionTaxRate',
        ),
    ]
