# Generated by Django 5.2.11 on 2026-02-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0015_alter_localgovernmentunit_options_companyprofile_lgu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='fiscal_cert_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='fiskalni certifikat (datoteka)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='fiscal_cert_issuer',
            field=models.CharField(blank=True, default='', editable=False, max_length=512),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='fiscal_cert_p12',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='fiscal_cert_pass',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='fiskalni certifikat (lozinka)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='fiscal_cert_subject',
            field=models.CharField(blank=True, default='', editable=False, max_length=512),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='fiscal_cert_valid_from',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='fiscal_cert_valid_to',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
