# Generated by Django 5.2.10 on 2026-01-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rm_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("name2", models.CharField(blank=True, default="", max_length=255)),
                ("card_number", models.CharField(blank=True, default="", max_length=50)),
                ("tax_number", models.CharField(blank=True, default="", max_length=50)),
            ],
            options={
                "verbose_name": "Kontakt",
                "verbose_name_plural": "Kontakti",
            },
        ),
    ]
