# Generated by Django 5.2.10 on 2026-01-18 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Stuff',
        ),
    ]
