# Generated by Django 5.2.10 on 2026-01-18 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_stuff_delete_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stuff',
            options={'verbose_name': 'Zaposlenik', 'verbose_name_plural': 'Zaposlenici'},
        ),
    ]
