# Generated by Django 5.2.10 on 2026-01-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_alter_stuff_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rm_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("town", models.CharField(blank=True, default="", max_length=255)),
                ("street", models.CharField(blank=True, default="", max_length=255)),
                ("tax_number", models.CharField(blank=True, default="", max_length=50)),
                ("mobile_devices", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Dobavljač",
                "verbose_name_plural": "Dobavljači",
            },
        ),
    ]
