# Generated by Django 5.2.10 on 2026-01-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='orders_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
