# Generated by Django 5.2.12 on 2026-04-15 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0016_companyprofile_fiscal_cert_filename_and_more'),
        ('contacts', '0007_set_supplier_show_prices_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='default_payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='configuration.paymenttype', verbose_name='zadani tip placanja'),
        ),
    ]
