# Generated by Django 5.2.10 on 2026-01-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
