# Generated by Django 5.2.10 on 2026-01-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0002_unitofmeasuredata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesGroupData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Prodajna grupa',
                'verbose_name_plural': 'Prodajne grupe',
            },
        ),
        migrations.AlterModelOptions(
            name='artikl',
            options={'verbose_name': 'Artikl', 'verbose_name_plural': 'Artikli'},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasuredata',
            options={'verbose_name': 'Jedinica mjere', 'verbose_name_plural': 'Jedinice mjere'},
        ),
    ]
