# Generated by Django 5.2.10 on 2026-01-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0003_salesgroupdata_alter_artikl_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyboardGroupData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Tipkovna grupa',
                'verbose_name_plural': 'Tipkovne grupe',
            },
        ),
    ]
