# Generated by Django 5.2.10 on 2026-01-17 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0005_basegroupdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtiklDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('external_code', models.CharField(blank=True, max_length=50)),
                ('base_group_id', models.IntegerField(blank=True, null=True)),
                ('base_group_name', models.CharField(blank=True, max_length=150)),
                ('sales_group_id', models.IntegerField(blank=True, null=True)),
                ('sales_group_name', models.CharField(blank=True, max_length=150)),
                ('keyboard_group_id', models.IntegerField(blank=True, null=True)),
                ('keyboard_group_name', models.CharField(blank=True, max_length=150)),
                ('unit_of_measure_id', models.IntegerField(blank=True, null=True)),
                ('unit_of_measure_name', models.CharField(blank=True, max_length=100)),
                ('standard_uom_id', models.IntegerField(blank=True, null=True)),
                ('standard_uom_name', models.CharField(blank=True, max_length=100)),
                ('quantity_in_suom', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('spillage_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ordinal', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('point_of_issue_id', models.IntegerField(blank=True, null=True)),
                ('point_of_issue_name', models.CharField(blank=True, max_length=150)),
                ('is_for_sale', models.BooleanField(default=False)),
                ('is_purchased', models.BooleanField(default=False)),
                ('is_product', models.BooleanField(default=False)),
                ('is_commodity', models.BooleanField(default=False)),
                ('is_immaterial', models.BooleanField(default=False)),
                ('is_used_on_pos', models.BooleanField(default=False)),
                ('is_package', models.BooleanField(default=False)),
                ('is_negative_quantity_allowed', models.BooleanField(default=False)),
                ('no_discount', models.BooleanField(default=False)),
                ('has_return_fee', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('print_on_pricelist', models.BooleanField(default=False)),
                ('artikl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='artikli.artikl')),
            ],
            options={
                'verbose_name': 'Detalj artikla',
                'verbose_name_plural': 'Detalji artikala',
            },
        ),
    ]
