# Generated by Django 5.2.10 on 2026-01-17 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0006_artikldetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikldetail',
            name='base_group_id',
        ),
        migrations.RemoveField(
            model_name='artikldetail',
            name='base_group_name',
        ),
        migrations.RemoveField(
            model_name='artikldetail',
            name='keyboard_group_id',
        ),
        migrations.RemoveField(
            model_name='artikldetail',
            name='keyboard_group_name',
        ),
        migrations.RemoveField(
            model_name='artikldetail',
            name='sales_group_id',
        ),
        migrations.RemoveField(
            model_name='artikldetail',
            name='sales_group_name',
        ),
        migrations.AddField(
            model_name='artikldetail',
            name='base_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikl_details_base', to='artikli.basegroupdata', to_field='rm_id'),
        ),
        migrations.AddField(
            model_name='artikldetail',
            name='keyboard_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikl_details_keyboard', to='artikli.keyboardgroupdata', to_field='rm_id'),
        ),
        migrations.AddField(
            model_name='artikldetail',
            name='sales_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikl_details_sales', to='artikli.salesgroupdata', to_field='rm_id'),
        ),
    ]
