# Generated by Django 5.2.10 on 2026-01-17 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0007_remove_artikldetail_base_group_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikldetail',
            name='unit_of_measure_id',
        ),
        migrations.RemoveField(
            model_name='artikldetail',
            name='unit_of_measure_name',
        ),
        migrations.AddField(
            model_name='artikldetail',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikl_details_unit', to='artikli.unitofmeasuredata', to_field='rm_id'),
        ),
    ]
