# Generated by Django 5.2.10 on 2026-01-17 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0008_remove_artikldetail_unit_of_measure_id_and_more'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikldetail',
            name='point_of_issue_id',
        ),
        migrations.RemoveField(
            model_name='artikldetail',
            name='point_of_issue_name',
        ),
        migrations.AddField(
            model_name='artikldetail',
            name='point_of_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikl_details_point', to='configuration.pointofissuedata', to_field='rm_id'),
        ),
    ]
