# Generated by Django 5.2.10 on 2026-01-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0009_remove_artikldetail_point_of_issue_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikl',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artikli/'),
        ),
        migrations.AddField(
            model_name='artikl',
            name='intrinsic_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artikl',
            name='intrinsic_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artikl',
            name='rendered_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artikl',
            name='rendered_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
