# Generated by Django 5.2.10 on 2026-01-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0010_artikl_image_artikl_intrinsic_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikl',
            name='intrinsic_height',
        ),
        migrations.RemoveField(
            model_name='artikl',
            name='intrinsic_width',
        ),
        migrations.RemoveField(
            model_name='artikl',
            name='rendered_height',
        ),
        migrations.RemoveField(
            model_name='artikl',
            name='rendered_width',
        ),
    ]
