# Generated by Django 5.2.10 on 2026-01-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0011_remove_artikl_intrinsic_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikl',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
