# Generated by Django 5.2.10 on 2026-01-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0012_alter_artikl_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikl',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
