# Generated by Django 5.2.10 on 2026-01-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0013_artikl_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikl',
            name='rm_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
