# Generated by Django 5.2.10 on 2026-01-20 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0014_alter_artikl_rm_id'),
        ('configuration', '0004_taxgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikl',
            name='tax_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikli', to='configuration.taxgroup', verbose_name='porezna grupa'),
        ),
    ]
