# Generated by Django 5.2.10 on 2026-01-21 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0015_artikl_tax_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_eur', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='iznos u EUR')),
            ],
            options={
                'verbose_name': 'Povratna naknada',
                'verbose_name_plural': 'Povratne naknade',
            },
        ),
        migrations.AddField(
            model_name='artikl',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikli', to='artikli.deposit', verbose_name='povratna naknada'),
        ),
    ]
