# Generated by Django 5.2.10 on 2026-01-26 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0016_deposit_artikl_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionTaxCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PnP kategorija',
                'verbose_name_plural': 'PnP kategorije',
            },
        ),
        migrations.AddField(
            model_name='artikl',
            name='pnp_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikli', to='artikli.consumptiontaxcategory', verbose_name='PnP kategorija'),
        ),
    ]
