# Generated by Django 5.2.10 on 2026-01-26 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0019_move_consumption_tax_category_to_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='artikli.drinkcategory')),
            ],
            options={
                'verbose_name': 'Kategorija napitaka',
                'verbose_name_plural': 'Kategorije napitaka',
                'ordering': ['parent_id', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='artikl',
            name='drink_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikli', to='artikli.drinkcategory', verbose_name='Kategorija napitaka'),
        ),
        migrations.AddConstraint(
            model_name='drinkcategory',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='uniq_category_name_per_parent'),
        ),
    ]
