# Generated by Django 5.2.10 on 2026-01-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0021_seed_drink_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikl',
            name='is_sellable',
            field=models.BooleanField(default=True, verbose_name='Prodajni artikl'),
        ),
        migrations.AddField(
            model_name='artikl',
            name='is_stock_item',
            field=models.BooleanField(default=False, verbose_name='Skladisni artikl'),
        ),
    ]
