# Generated by Django 5.2.10 on 2026-01-27 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0022_artikl_is_sellable_artikl_is_stock_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Normativ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.OneToOneField(limit_choices_to={'is_sellable': True}, on_delete=django.db.models.deletion.CASCADE, related_name='normativ', to='artikli.artikl', verbose_name='Prodajni (virtualni) artikl')),
            ],
            options={
                'verbose_name': 'Normativ',
                'verbose_name_plural': 'Normativi',
            },
        ),
        migrations.CreateModel(
            name='NormativItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, help_text='npr. caj kutija 0.0500, kava kg 0.0090, limun kg 0.0400, med kom 1.0000', max_digits=12, verbose_name='Kolicina po 1 prodaji')),
                ('ingredient', models.ForeignKey(limit_choices_to={'is_stock_item': True}, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_normatives', to='artikli.artikl', verbose_name='Skladisni artikl')),
                ('normativ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='artikli.normativ')),
            ],
            options={
                'verbose_name': 'Stavka normativa',
                'verbose_name_plural': 'Stavke normativa',
                'constraints': [models.UniqueConstraint(fields=('normativ', 'ingredient'), name='uniq_normativ_ingredient')],
            },
        ),
    ]
