# Generated by Django 5.2.10 on 2026-01-27 13:11

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0023_normativ_normativitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drinkcategory',
            options={'ordering': ['tree_id', 'lft'], 'verbose_name': 'Kategorija napitaka', 'verbose_name_plural': 'Kategorije napitaka'},
        ),
        migrations.AddField(
            model_name='drinkcategory',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drinkcategory',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drinkcategory',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drinkcategory',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drinkcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='artikli.drinkcategory'),
        ),
    ]
