# Generated by Django 5.2.10 on 2026-01-29 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0024_alter_drinkcategory_options_drinkcategory_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drinkcategory',
            options={'ordering': ['tree_id', 'lft'], 'verbose_name': 'Kategorija pića', 'verbose_name_plural': 'Kategorije pića'},
        ),
        migrations.AlterField(
            model_name='artikl',
            name='drink_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikli', to='artikli.drinkcategory', verbose_name='Kategorija pića'),
        ),
    ]
