# Generated by Django 5.2.10 on 2026-01-20 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artikli', '0014_alter_artikl_rm_id'),
        ('contacts', '0004_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='contacts.supplier')),
            ],
            options={
                'verbose_name': 'Narudzba',
                'verbose_name_plural': 'Narudzbe',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('artikl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='artikli.artikl')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='artikli.unitofmeasuredata')),
            ],
            options={
                'verbose_name': 'Stavka narudzbe',
                'verbose_name_plural': 'Stavke narudzbi',
            },
        ),
    ]
