# Generated by Django 5.2.10 on 2026-01-20 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0014_alter_artikl_rm_id'),
        ('contacts', '0005_supplier_orders_email'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='email poslan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(verbose_name='datum narudzbe'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='contacts.supplier', verbose_name='dobavljac'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='artikl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='artikli.artikl', verbose_name='artikl'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='narudzba'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='kolicina'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_of_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='artikli.unitofmeasuredata', verbose_name='jedinica mjere'),
        ),
    ]
