# Generated by Django 5.2.10 on 2026-01-20 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0015_artikl_tax_group'),
        ('contacts', '0005_supplier_orders_email'),
        ('orders', '0002_order_email_sent_alter_order_ordered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='cijena')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivno')),
                ('artikl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='artikli.artikl', verbose_name='artikl')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='contacts.supplier', verbose_name='dobavljac')),
                ('unit_of_measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_prices', to='artikli.unitofmeasuredata', verbose_name='jedinica mjere')),
            ],
            options={
                'verbose_name': 'Cjenik dobavljaca',
                'verbose_name_plural': 'Cjenici dobavljaca',
            },
        ),
    ]
