# Generated by Django 5.2.10 on 2026-01-20 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0015_artikl_tax_group'),
        ('contacts', '0005_supplier_orders_email'),
        ('orders', '0003_supplierprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='datum kreiranja')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='vrijedi od')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='vrijedi do')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivno')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='contacts.supplier', verbose_name='dobavljac')),
            ],
            options={
                'verbose_name': 'Cjenik dobavljača',
                'verbose_name_plural': 'Cjenici dobavljača',
            },
        ),
        migrations.CreateModel(
            name='SupplierPriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='cijena')),
                ('artikl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_price_items', to='artikli.artikl', verbose_name='artikl')),
                ('unit_of_measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_price_items', to='artikli.unitofmeasuredata', verbose_name='jedinica mjere')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.supplierpricelist', verbose_name='cjenik')),
            ],
            options={
                'verbose_name': 'Stavka cjenika',
                'verbose_name_plural': 'Stavke cjenika',
            },
        ),
        migrations.DeleteModel(
            name='SupplierPrice',
        ),
    ]
