# Generated by Django 5.2.10 on 2026-01-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_supplierpricelist_supplierpriceitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpricelist',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='valuta'),
        ),
        migrations.AlterField(
            model_name='supplierpriceitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cijena'),
        ),
    ]
