# Generated by Django 5.2.10 on 2026-01-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='bruto iznos'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='netto iznos'),
        ),
    ]
