# Generated by Django 5.2.10 on 2026-01-20 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_paymenttype'),
        ('orders', '0007_order_total_gross_order_total_net'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='configuration.paymenttype', verbose_name='tip placanja'),
        ),
    ]
