# Generated by Django 5.2.10 on 2026-01-20 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0015_artikl_tax_group'),
        ('configuration', '0006_paymenttype_rm_id'),
        ('contacts', '0005_supplier_orders_email'),
        ('orders', '0008_order_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaris_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='remaris id')),
                ('date', models.DateField(verbose_name='datum')),
                ('date_modified', models.DateTimeField(blank=True, null=True, verbose_name='datum izmjene')),
                ('document_type', models.CharField(default='10', max_length=10, verbose_name='tip dokumenta')),
                ('is_in_pdv_system', models.BooleanField(default=True, verbose_name='u PDV sustavu')),
                ('warehouse_id', models.IntegerField(blank=True, null=True, verbose_name='skladiste id')),
                ('export_document_type_id', models.IntegerField(blank=True, null=True, verbose_name='export tip dokumenta id')),
                ('invoice_code', models.CharField(blank=True, default='', max_length=100, verbose_name='broj racuna')),
                ('delivery_note', models.CharField(blank=True, default='', max_length=100, verbose_name='broj otpremnice')),
                ('is_r_invoice', models.BooleanField(default=False, verbose_name='R racun')),
                ('is_internal_input', models.BooleanField(default=False, verbose_name='interni ulaz')),
                ('is_nonmaterial_input', models.BooleanField(default=False, verbose_name='nematerijalni ulaz')),
                ('purchase_order', models.CharField(blank=True, default='', max_length=100, verbose_name='narudzbenica')),
                ('description', models.TextField(blank=True, default='', verbose_name='opis')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ukupno')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='stornirano')),
                ('submit_command', models.CharField(default='_save_', max_length=50, verbose_name='submit')),
                ('raw_payload', models.JSONField(blank=True, null=True, verbose_name='raw payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='kreirano')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_inputs', to='orders.order', verbose_name='narudzba')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inputs', to='configuration.paymenttype', verbose_name='tip placanja')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_inputs', to='contacts.supplier', verbose_name='dobavljac')),
            ],
            options={
                'verbose_name': 'Primka',
                'verbose_name_plural': 'Primke',
            },
        ),
        migrations.CreateModel(
            name='WarehouseInputItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True, verbose_name='product id')),
                ('product_name', models.CharField(blank=True, default='', max_length=255, verbose_name='naziv artikla')),
                ('unit_name', models.CharField(blank=True, default='', max_length=100, verbose_name='naziv jedinice')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='kolicina')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='cijena')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ukupno')),
                ('buying_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='nabavna cijena')),
                ('gross_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='bruto')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='pdv stopa')),
                ('calculate_tax', models.BooleanField(default=True, verbose_name='racunaj pdv')),
                ('rebate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='rabat')),
                ('margin', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='marza')),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='prodajna cijena')),
                ('ordinal', models.IntegerField(blank=True, null=True, verbose_name='redni broj')),
                ('base_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='bazna kolicina')),
                ('vat_prepayment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='predujam pdv')),
                ('calculate_spillage', models.BooleanField(blank=True, null=True, verbose_name='izljev')),
                ('price_on_stock_card', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='cijena na kartici')),
                ('last_input_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='zadnja nabavna cijena')),
                ('guid', models.CharField(blank=True, default='', max_length=100, verbose_name='guid')),
                ('parent_guid', models.CharField(blank=True, default='', max_length=100, verbose_name='parent guid')),
                ('artikl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_input_items', to='artikli.artikl', verbose_name='artikl')),
                ('unit_of_measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_input_items', to='artikli.unitofmeasuredata', verbose_name='jedinica mjere')),
                ('warehouse_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.warehouseinput', verbose_name='primka')),
            ],
            options={
                'verbose_name': 'Stavka primke',
                'verbose_name_plural': 'Stavke primke',
            },
        ),
    ]
