# Generated by Django 5.2.10 on 2026-01-20 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_warehouseinput_warehouseinputitem'),
        ('stock', '0016_warehousetransfer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseinput',
            name='warehouse_id',
        ),
        migrations.AddField(
            model_name='warehouseinput',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inputs', to='stock.warehouseid', verbose_name='skladiste'),
        ),
    ]
