# Generated by Django 5.2.10 on 2026-01-20 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_warehouseinput_warehouse_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseinput',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inputs_purchase_orders', to='orders.order', verbose_name='narudzbenica'),
        ),
    ]
