# Generated by Django 5.2.10 on 2026-01-20 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_paymenttype_rm_id'),
        ('contacts', '0005_supplier_orders_email'),
        ('orders', '0012_rename_order_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='configuration.paymenttype', verbose_name='tip placanja'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='contacts.supplier', verbose_name='dobavljac'),
        ),
    ]
