# Generated by Django 5.2.10 on 2026-01-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_purchaseorder_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='primka_created',
            field=models.BooleanField(default=False, verbose_name='primka kreirana'),
        ),
    ]
