# Generated by Django 5.2.10 on 2026-01-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_supplier_orders_email'),
        ('orders', '0015_purchaseorder_status_and_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='total_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='povratna naknada'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_with_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ukupno s povratnom naknadom'),
        ),
    ]
