# Generated by Django 5.2.10 on 2026-01-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_supplier_orders_email'),
        ('orders', '0016_purchaseorder_total_deposit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_with_deposit',
        ),
    ]
