# Generated by Django 5.2.10 on 2026-01-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_supplierpriceitem_unique_artikl'),
        ('orders', '0017_remove_purchaseorder_total_with_deposit_and_more'),
    ]

    operations = [
    ]
