# Generated by Django 5.2.10 on 2026-01-22 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_supplier_orders_email'),
        ('orders', '0019_alter_warehouseinput_is_r_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='ordered_at',
            field=models.DateTimeField(verbose_name='datum narudžbe'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('created', 'Kreirana'), ('sent', 'Poslana'), ('confirmed', 'Potvrđena'), ('received', 'Primljena'), ('canceled', 'Otkazana')], default='created', max_length=20, verbose_name='status narudžbe'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='contacts.supplier', verbose_name='dobavljač'),
        ),
    ]
