# Generated by Django 5.2.10 on 2026-01-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_purchaseorder_ordered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('created', 'Kreirana'), ('sent', 'Poslana'), ('confirmed', 'Potvrđena'), ('received', 'Zaprimljena'), ('canceled', 'Otkazana')], default='created', max_length=20, verbose_name='status narudžbe'),
        ),
    ]
