# Generated by Django 5.2.10 on 2026-01-23 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_journalentry_reversed_entry'),
        ('orders', '0022_warehouseinput_document_type_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseinput',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_inputs', to='accounting.journalentry', verbose_name='temeljnica'),
        ),
        migrations.AlterField(
            model_name='warehouseinput',
            name='document_type_code',
            field=models.CharField(default='10', max_length=10, verbose_name='tip dokumenta (sifra)'),
        ),
    ]
