# Generated by Django 5.2.10 on 2026-01-23 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_warehouseinput_journal_entry_and_more'),
        ('stock', '0020_stockmove_stocklot_stockmoveline_stockallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseinput',
            name='stock_move',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_input', to='stock.stockmove', verbose_name='skladisno kretanje'),
        ),
    ]
