# Generated by Django 5.2.11 on 2026-02-12 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_ledger_external_org_id'),
        ('orders', '0026_purchaseorder_received_all_status'),
        ('stock', '0038_inventory_counted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseinput',
            name='supplier_return_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_return_inputs', to='accounting.journalentry', verbose_name='financijsko terecenje povrata'),
        ),
        migrations.AddField(
            model_name='warehouseinput',
            name='supplier_return_stock_move',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_return_input', to='stock.stockmove', verbose_name='povrat dobavljacu (skladiste)'),
        ),
    ]
