# Generated by Django 5.2.11 on 2026-02-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_supplierinvoice_and_copy_from_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('created', 'Kreirana'), ('sent', 'Poslana'), ('confirmed', 'Potvrđena'), ('received', 'Zaprimljena'), ('received_all', 'Sve stavke s narudžbe su zaprimljene'), ('canceled', 'Otkazana')], default='created', max_length=20, verbose_name='status narudžbe'),
        ),
    ]
