# Generated by Django 5.2.11 on 2026-03-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpricelist',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='naziv cjenika'),
        ),
    ]
