# Generated by Django 5.2.12 on 2026-05-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_supplierpricelist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='zadnja izmjena'),
        ),
    ]
