# Generated by Django 5.2.11 on 2026-04-01 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0032_supplierpricelist_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
                verbose_name="zadnja izmjena",
            ),
            preserve_default=False,
        ),
    ]
