# Generated by Django 5.2.10 on 2026-01-23 19:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_ledger_company_profile'),
        ('contacts', '0005_supplier_orders_email'),
        ('orders', '0023_warehouseinput_journal_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('received_at', models.DateField(blank=True, null=True)),
                ('deposit_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('paid_cash', models.BooleanField(default=False)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('inputs', models.ManyToManyField(blank=True, related_name='supplier_invoices', to='orders.warehouseinput')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice', to='accounting.journalentry')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.supplier')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('supplier', 'invoice_number'), name='uq_supplier_invoice_number')],
            },
        ),
    ]
