# Generated by Django 5.2.10 on 2026-01-24 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_ledger_company_profile'),
        ('purchases', '0002_supplierinvoice_cash_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierinvoice',
            options={'verbose_name': 'Ulazni račun', 'verbose_name_plural': 'Ulazni računi'},
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='ap_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Neplaceno'), ('partial', 'Djelomicno'), ('paid', 'Placeno')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='payment_terms',
            field=models.CharField(choices=[('cash', 'Gotovina'), ('deferred', 'Odgoda')], default='cash', max_length=20),
        ),
    ]
