# Generated by Django 5.2.10 on 2026-01-24 03:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_ledger_company_profile'),
        ('purchases', '0003_alter_supplierinvoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
    ]
