# Generated by Django 5.2.10 on 2026-01-26 00:00

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalesInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rm_number", models.IntegerField(unique=True)),
                ("issued_on", models.DateField()),
                ("issued_at", models.DateTimeField()),
                ("location_name", models.CharField(blank=True, default="", max_length=255)),
                ("buyer_name", models.CharField(blank=True, default="", max_length=255)),
                ("waiter_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                    ),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=10)),
                ("organization_id", models.IntegerField(blank=True, null=True)),
                ("location_id", models.IntegerField(blank=True, null=True)),
                ("pos_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Racun (promet)",
                "verbose_name_plural": "Racuni (promet)",
            },
        ),
        migrations.CreateModel(
            name="SalesInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="items",
                        to="sales.salesinvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stavka racuna (promet)",
                "verbose_name_plural": "Stavke racuna (promet)",
            },
        ),
        migrations.AddConstraint(
            model_name="salesinvoice",
            constraint=models.UniqueConstraint(
                fields=("rm_number", "issued_on"),
                name="uq_sales_invoice_number_date",
            ),
        ),
    ]
