# Generated by Django 5.2.10 on 2026-01-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="salesinvoice",
            name="uq_sales_invoice_number_date",
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="rm_number",
            field=models.IntegerField(unique=True),
        ),
    ]
