# Generated by Django 5.2.10 on 2026-01-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0019_move_consumption_tax_category_to_configuration'),
        ('sales', '0002_alter_salesinvoice_rm_number_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='artikl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoice_items', to='artikli.artikl'),
        ),
    ]
