# Generated by Django 5.2.10 on 2026-01-27 15:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0024_alter_drinkcategory_options_drinkcategory_level_and_more'),
        ('sales', '0003_salesinvoiceitem_artikl'),
        ('stock', '0033_warehousestock_internal_avg_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(verbose_name='Vrijeme')),
                ('reason', models.CharField(choices=[('guests', 'Gosti'), ('compliment', 'Castilo se'), ('promo', 'Promocija'), ('other', 'Ostalo')], default='guests', max_length=30, verbose_name='Razlog reprezentacije')),
                ('note', models.TextField(blank=True, default='', verbose_name='Napomena')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representations', to=settings.AUTH_USER_MODEL, verbose_name='Korisnik')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representations', to='stock.warehouseid', to_field='rm_id', verbose_name='Skladiste')),
            ],
            options={
                'verbose_name': 'Reprezentacija',
                'verbose_name_plural': 'Reprezentacije',
            },
        ),
        migrations.CreateModel(
            name='RepresentationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Kolicina')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cijena')),
                ('artikl', models.ForeignKey(limit_choices_to={'is_sellable': True}, on_delete=django.db.models.deletion.PROTECT, related_name='representation_items', to='artikli.artikl', verbose_name='Artikl')),
                ('representation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.representation')),
            ],
            options={
                'verbose_name': 'Stavka reprezentacije',
                'verbose_name_plural': 'Stavke reprezentacije',
            },
        ),
    ]
