# Generated by Django 5.2.10 on 2026-01-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_representation_representationitem'),
        ('stock', '0033_warehousestock_internal_avg_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='occurred_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vrijeme'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='representations', to='stock.warehouseid', to_field='rm_id', verbose_name='Skladiste'),
        ),
    ]
