# Generated by Django 5.2.10 on 2026-01-29 00:00

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_representation_reason_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesinvoice",
            name="net_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
    ]
