# Generated by Django 5.2.10 on 2026-01-29 00:00

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_ledger_company_profile"),
        ("sales", "0007_salesinvoice_net_vat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesZPosting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("issued_on", models.DateField()),
                ("location_id", models.IntegerField(blank=True, null=True)),
                ("pos_id", models.IntegerField(blank=True, null=True)),
                ("net_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("vat_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("total_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("journal_entry", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sales_z_postings", to="accounting.journalentry")),
                ("posted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_z_postings", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Z knjiženje (promet)",
                "verbose_name_plural": "Z knjiženja (promet)",
            },
        ),
        migrations.AddConstraint(
            model_name="saleszposting",
            constraint=models.UniqueConstraint(fields=("issued_on", "location_id", "pos_id"), name="uq_sales_z_posting"),
        ),
    ]
