# Generated by Django 5.2.10 on 2026-01-29 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_ledger_company_profile"),
        ("sales", "0008_sales_z_posting"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleszposting",
            name="cash_account",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="accounting.account"),
        ),
        migrations.AddField(
            model_name="saleszposting",
            name="revenue_account",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="accounting.account"),
        ),
        migrations.AddField(
            model_name="saleszposting",
            name="vat_account",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="accounting.account"),
        ),
        migrations.AlterField(
            model_name="saleszposting",
            name="journal_entry",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="sales_z_postings", to="accounting.journalentry"),
        ),
    ]
