# Generated by Django 5.2.10 on 2026-01-29 00:00

from django.db import migrations, models


def forward_fill_fk(apps, schema_editor):
    Ledger = apps.get_model("accounting", "Ledger")
    WarehouseId = apps.get_model("stock", "WarehouseId")
    Pos = apps.get_model("pos", "Pos")
    SalesInvoice = apps.get_model("sales", "SalesInvoice")
    SalesZPosting = apps.get_model("sales", "SalesZPosting")

    ledger_map = {
        l.external_organization_id: l.id
        for l in Ledger.objects.exclude(external_organization_id__isnull=True)
    }
    warehouse_map = {
        w.external_location_id: w.id
        for w in WarehouseId.objects.exclude(external_location_id__isnull=True)
    }
    pos_map = {p.external_pos_id: p.id for p in Pos.objects.all()}

    default_ledger_id = Ledger.objects.values_list("id", flat=True).first()

    for inv_id, ledger_raw, warehouse_raw, pos_raw in SalesInvoice.objects.values_list(
        "id", "ledger_id", "warehouse_id", "pos_id"
    ).iterator():
        ledger_id = ledger_map.get(ledger_raw) or default_ledger_id
        warehouse_id = warehouse_map.get(warehouse_raw)
        pos_id = pos_map.get(pos_raw)
        SalesInvoice.objects.filter(id=inv_id).update(
            ledger_id=ledger_id,
            warehouse_id=warehouse_id,
            pos_id=pos_id,
        )

    for posting_id, warehouse_raw, pos_raw in SalesZPosting.objects.values_list(
        "id", "warehouse_id", "pos_id"
    ).iterator():
        warehouse_id = warehouse_map.get(warehouse_raw)
        pos_id = pos_map.get(pos_raw)
        SalesZPosting.objects.filter(id=posting_id).update(
            ledger_id=default_ledger_id,
            warehouse_id=warehouse_id,
            pos_id=pos_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_ledger_external_org_id"),
        ("stock", "0034_warehouseid_external_location_id"),
        ("pos", "0001_initial"),
        ("sales", "0009_saleszposting_accounts_and_journal_nullable"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="salesinvoice",
                    name="ledger",
                    field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="sales_invoices", to="accounting.ledger", db_column="organization_id"),
                ),
                migrations.AddField(
                    model_name="salesinvoice",
                    name="warehouse",
                    field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="sales_invoices", to="stock.warehouseid", db_column="location_id"),
                ),
                migrations.AddField(
                    model_name="salesinvoice",
                    name="pos",
                    field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="sales_invoices", to="pos.pos", db_column="pos_id"),
                ),
                migrations.AddField(
                    model_name="saleszposting",
                    name="warehouse",
                    field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="sales_z_postings", to="stock.warehouseid", db_column="location_id"),
                ),
                migrations.AddField(
                    model_name="saleszposting",
                    name="pos",
                    field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="sales_z_postings", to="pos.pos", db_column="pos_id"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="saleszposting",
            name="ledger",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="sales_z_postings", to="accounting.ledger"),
        ),
        migrations.RunPython(forward_fill_fk, migrations.RunPython.noop),
    ]
