# Generated by Django 5.2.10 on 2026-01-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0010_salesinvoice_saleszposting_fk"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="saleszposting",
            name="uq_sales_z_posting",
        ),
        migrations.AddConstraint(
            model_name="saleszposting",
            constraint=models.UniqueConstraint(fields=("issued_on", "ledger", "warehouse", "pos"), name="uq_sales_z_posting"),
        ),
    ]
