# Generated by Codex on 2026-01-29

from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_ledger_external_org_id"),
        ("sales", "0011_update_saleszposting_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleszposting",
            name="pnp_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="saleszposting",
            name="pnp_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
    ]
