# Generated by Django 5.2.10 on 2026-01-29 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        ('sales', '0012_saleszposting_pnp_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='pos_id',
        ),
        migrations.RemoveField(
            model_name='saleszposting',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='saleszposting',
            name='pos_id',
        ),
        migrations.AlterField(
            model_name='saleszposting',
            name='pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_z_postings', to='pos.pos'),
        ),
    ]
