# Generated by Codex on 2026-01-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0013_remove_salesinvoice_location_id_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE sales_salesinvoice
                ADD COLUMN IF NOT EXISTS organization_id bigint NULL,
                ADD COLUMN IF NOT EXISTS location_id bigint NULL,
                ADD COLUMN IF NOT EXISTS pos_id bigint NULL;
            ALTER TABLE sales_saleszposting
                ADD COLUMN IF NOT EXISTS location_id bigint NULL,
                ADD COLUMN IF NOT EXISTS pos_id bigint NULL;
            """,
            reverse_sql="""
            ALTER TABLE sales_saleszposting
                DROP COLUMN IF EXISTS pos_id,
                DROP COLUMN IF EXISTS location_id;
            ALTER TABLE sales_salesinvoice
                DROP COLUMN IF EXISTS pos_id,
                DROP COLUMN IF EXISTS location_id,
                DROP COLUMN IF EXISTS organization_id;
            """,
        ),
    ]
