# Generated by Django 5.2.10 on 2026-01-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_restore_salesinvoice_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='stock_out_posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
