# Generated by Django 5.2.10 on 2026-01-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_salesinvoiceitem_stock_out_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='representationitem',
            name='transfer_posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
