# Generated by Django 5.2.10 on 2026-01-31 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_representationitem_transfer_posted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('success', 'Success'), ('error', 'Error')], default='draft', max_length=20)),
                ('zki', models.CharField(blank=True, default='', max_length=64)),
                ('jir', models.CharField(blank=True, default='', max_length=64)),
                ('payment_type', models.CharField(blank=True, default='CASH', max_length=20)),
                ('xml_request', models.TextField(blank=True, default='')),
                ('xml_response', models.TextField(blank=True, default='')),
                ('qr_payload', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_receipt', to='sales.salesinvoice')),
            ],
            options={
                'verbose_name': 'Fiskalni racun',
                'verbose_name_plural': 'Fiskalni racuni',
            },
        ),
    ]
