# Generated by Django 5.2.10 on 2026-01-31 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikli', '0025_alter_drinkcategory_options_and_more'),
        ('pos', '0005_posscreen_posscreenitem'),
        ('sales', '0017_fiscalreceipt'),
        ('stock', '0036_stockcostsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Naziv')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('is_default', models.BooleanField(default=False, verbose_name='Zadani')),
                ('valid_from', models.DateTimeField(verbose_name='Vrijedi od')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Vrijedi do')),
                ('note', models.TextField(blank=True, default='', verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_price_lists', to='pos.pos', verbose_name='POS')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_price_lists', to='stock.warehouseid', verbose_name='Skladiste')),
            ],
            options={
                'verbose_name': 'Prodajni cjenik',
                'verbose_name_plural': 'Prodajni cjenici',
                'ordering': ['-valid_from', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalesPriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Naziv')),
                ('rule_type', models.CharField(choices=[('happy_hour', 'Happy hour'), ('promo', 'Promocija'), ('event', 'Događaj')], max_length=20, verbose_name='Tip')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivno')),
                ('valid_from', models.DateTimeField(verbose_name='Vrijedi od')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Vrijedi do')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Prioritet')),
                ('adjust_type', models.CharField(choices=[('percent', 'Postotak'), ('amount', 'Iznos'), ('set_price', 'Fiksna cijena')], max_length=20, verbose_name='Model')),
                ('value', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Vrijednost')),
                ('note', models.TextField(blank=True, default='', verbose_name='Napomena')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='sales.salespricelist', verbose_name='Cjenik')),
            ],
            options={
                'verbose_name': 'Pravilo cijena',
                'verbose_name_plural': 'Pravila cijena',
                'ordering': ['-priority', 'valid_from'],
            },
        ),
        migrations.CreateModel(
            name='SalesPriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price_gross', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cijena (bruto)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivno')),
                ('note', models.TextField(blank=True, default='', verbose_name='Napomena')),
                ('artikl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_price_items', to='artikli.artikl', verbose_name='Artikl')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salespricelist', verbose_name='Cjenik')),
            ],
            options={
                'verbose_name': 'Stavka prodajnog cjenika',
                'verbose_name_plural': 'Stavke prodajnog cjenika',
                'constraints': [models.UniqueConstraint(fields=('price_list', 'artikl'), name='uniq_sales_pricelist_artikl')],
            },
        ),
        migrations.CreateModel(
            name='SalesPriceRuleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_price_rule_items', to='artikli.artikl', verbose_name='Artikl')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salespricerule', verbose_name='Pravilo')),
            ],
            options={
                'verbose_name': 'Stavka pravila cijena',
                'verbose_name_plural': 'Stavke pravila cijena',
                'constraints': [models.UniqueConstraint(fields=('rule', 'artikl'), name='uniq_sales_pricerule_artikl')],
            },
        ),
    ]
