# Generated by Django 5.2.10 on 2026-01-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0018_salespricelist_salespricerule_salespriceitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesinvoice",
            name="report_from",
            field=models.DateField(blank=True, null=True),
        ),
    ]
