# Generated by Django 5.2.10 on 2026-01-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_shift_turnover_close_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='is_card',
            field=models.BooleanField(default=False, verbose_name='kartica'),
        ),
    ]
