# Generated by Django 5.2.10 on 2026-02-01 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_salesinvoice_is_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftCashHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('OPENING', 'Preuzimanje'), ('CLOSING', 'Predaja')], max_length=10)),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('counted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('difference_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True, default='', verbose_name='napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='kreirano')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_cash_handovers', to=settings.AUTH_USER_MODEL, verbose_name='korisnik')),
                ('turnover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_handovers', to='sales.shiftturnover', verbose_name='promet smjene')),
            ],
            options={
                'verbose_name': 'Primopredaja blagajne',
                'verbose_name_plural': 'Primopredaje blagajne',
                'constraints': [models.UniqueConstraint(fields=('turnover', 'kind'), name='uniq_shift_cash_handover')],
            },
        ),
    ]
