# Generated by Django 5.2.10 on 2026-02-01 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_ledger_external_org_id'),
        ('sales', '0024_shiftcashhandover'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftcashhandover',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_handover', to='accounting.journalentry', verbose_name='temeljnica'),
        ),
    ]
