# Generated by Django 5.2.10 on 2026-02-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_shiftcashhandover_journal_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespriceitem',
            name='unit_price_gross',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cijena (bruto)'),
        ),
    ]
